# Generated by Django 2.1.3 on 2018-11-11 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eyes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyes_color', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('surname', models.TextField()),
                ('fathername', models.TextField()),
                ('birthdate', models.DateField()),
                ('country', models.ForeignKey(default='Russia', on_delete=django.db.models.deletion.CASCADE, to='TestCase.Country', to_field='country')),
                ('eyes_color', models.ForeignKey(default='Blue', on_delete=django.db.models.deletion.CASCADE, to='TestCase.Eyes', to_field='eyes_color')),
            ],
        ),
    ]
