# Generated by Django 2.1.3 on 2018-11-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0002_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
