# Generated by Django 2.1.3 on 2018-11-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0006_auto_20181111_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='static/foto')),
                ('album', models.ForeignKey(default='General', on_delete=django.db.models.deletion.CASCADE, to='TestCase.FotoAlbum', to_field='title')),
            ],
        ),
    ]
