# Generated by Django 2.1.3 on 2018-11-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0007_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='album',
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
