# Generated by Django 2.1.3 on 2018-11-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0009_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
