# Generated by Django 2.1.3 on 2018-11-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0010_foto_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyes',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='foto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestCase.Users'),
        ),
        migrations.AddField(
            model_name='fotoalbum',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestCase.Users'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='album',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='TestCase.FotoAlbum', to_field='title'),
        ),
    ]
