# Generated by Django 2.1.3 on 2018-11-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0013_auto_20181112_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='middle',
            field=models.ImageField(null=True, upload_to='static/foto/middle'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='static/foto/thumbnail'),
        ),
    ]
